/* Bundles the Figma plugin: inlines the icon registry into a single code.js.
 * Usage:  node figma-plugin/build.js
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { ICONS } from '../components/core/iconData.js';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const BUILDER = path.join(ROOT, 'src', 'builder.js');
const OUT = path.join(ROOT, 'code.js');

const names = Object.keys(ICONS).sort();
if (!names.length) {
  console.error('build failed: iconData.js exported no icons.');
  process.exit(1);
}

// Keep only what the plugin needs (viewBox + inner markup).
const slim = {};
for (const n of names) {
  slim[n] = { viewBox: ICONS[n].viewBox, path: ICONS[n].path };
}

const header =
  '/* TASAMA Design System — Figma plugin (generated by build.js, do not edit).\n' +
  ' * Source: src/builder.js + components/core/iconData.js\n' +
  ` * Icons: ${names.length}\n` +
  ' */\n' +
  `var ICON_SVG = ${JSON.stringify(slim)};\n\n`;

fs.writeFileSync(OUT, header + fs.readFileSync(BUILDER, 'utf8'), 'utf8');

const kb = (fs.statSync(OUT).size / 1024).toFixed(1);
console.log(`built code.js — ${names.length} icons, ${kb} KB`);
